book/urls.py
from django.urls import path

from book import views

app_name="book"

urlpatterns = [
    path("", views.library, name="index"),
    path("search/", views.book_search, name="book_search"),
    path("feedback", views.feedback, name="feedback"),
    path("<slug:book>/", views.book_detail, name="book_detail"),
    path('like_dislike', views.like_dislike, name='like_dislike'),
]

sitemi/urls.py
from django.contrib import admin
from django.urls import path, include
from sitemi import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("book.urls", namespace="book")),
    path("user/", include("users.urls", namespace="user")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import include, path
from users import views


app_name = "users"
urlpatterns = [
    path("registration", views.registration, name="registration"),
    path("", include("django.contrib.auth.urls")),
    path("profile", views.profile, name="profile"),
    path("logout", views.logout, name="logout"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.shortcuts import reverse

class User(AbstractUser):
    image = models.ImageField(upload_to="users_images", blank=True, null=True, verbose_name="Аватар")
    class Meta:
        db_table = "user"
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username
    
    def get_likes_given_no(self):
        likes = self.like_set.all()
        total_liked = 0
        for item in likes:
            if item.value=='Like':
                total_liked += 1
        return total_liked

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User

class UserLoginForm(AuthenticationForm):

    username = ()
    password = ()
    
    class Meta:
        model = User
        fields = ['username', 'password']


class UserRegistrationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        ]

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",
        )
    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from users.forms import ProfileForm, UserLoginForm, UserRegistrationForm
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required

from users.models import User


def registration(request):
    if request.method == "POST":
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            messages.success(request, f"{user.username}, Вы успешно зарегестрированы и вошли в аккаунт")
            return HttpResponseRedirect(reverse("user:login"))
    else:
        form = UserRegistrationForm()
    context={
        'title': "Home - Регистрация",
        'form': form
    }
    return render(request, "users/registration.html", context)

@login_required()
def profile(request):
    user=request.user
    if request.method == "POST":
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Профиль успешно обновлён")
            return HttpResponseRedirect(reverse("user:profile"))
    else:
        form = ProfileForm(instance=request.user)
    
    context = {
        "title": "Home - Кабинет",
        "form": form,
        "user": user,
        "header_bool": 1,
    }
    return render(request, "users/profile.html", context)

@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Вы вышли из аккаунта")
    auth.logout(request)
    return redirect(reverse('book:index'))

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

    {% block css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <link rel="stylesheet" href="/static/deps/css/login.css">
    {% endblock css %}
    {% block title %}
    {{  title  }}
    {% endblock title %}

{% block content %}
<div class="container">
    <form action="{% url "user:login" %}" method="post" class="form" id="loginForm">
        {% csrf_token %}
        <h1>Вход в аккаунт</h1>
        {% if form.non_field_errors %}
        
        <p>{{form.non_field_errors}}</p>
        {% endif %}
        <div class="form-group">
            <label for="id_email">Логин:</label>
            <input type="username" id="mail" name="username" 
            value = "{% if form.username.value %}{{form.username.value}}{% endif %}"
            placeholder="Введите ваш логин"
            required>
        </div>
        <div class="form-group">
            <label for="id_password">Пароль:</label>
          <input type="password" id="password" name="password" placeholder="Введите ваш пароль" required>
        </div>
            
        <div class="remember-forgot">
            <label><input type="checkbox">Запомнить</label>
            <a href="#">Забыли пароль?</a>
        </div>

        <button type="sumbit" class="btn">Войти</button>

        <div class="registration">
            <p>Нет аккаунта? <a href="{% url "user:registration" %}">Зарегистрироваться?</a></p>
        </div>
    </form>
</div>

{% endblock  %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block css %}

<link rel="stylesheet" href="{% static "deps/css/profile.css" %}">
{% endblock  %}
{% block header %}
<header>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">

            <a class="navbar-brand" href="{% url "book:index" %}"><img src="../static/deps/images/logo.svg" alt=""
                    style="width: 100px;"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item">
                        <a class="nav-link active" style="color: white;" aria-current="page" href="{% url "book:index" %}">Главная</a>
                    </li>
                </ul>

                <ul class="navbar-nav flex-grow-2 mx-auto mb-2 mb-lg-0 search">
                    <li>
                        <form class="d-flex flex-nowrap" role="search">
                            <input class="form-control me-0 form-search" type="search" placeholder="Найти" aria-label="Search">
                            <button class="btn btn-light btn-search" type="submit">
                                <svg xmlns="http://www.w3.org/2000/svg" width="17" height="25" fill="currentColor"
                                    class="bi bi-search" viewBox="0 0 16 16">
                                    <path
                                        d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0" />
                                </svg>
                            </button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
{% endblock header %}

{% block content %}
    <section>
        <!-- Профиль с данными пользователя -->
        <div class="col-md-5 mx-auto mt-4">
            <div class=" bg-white p-4 mb-4 mx-2 rounded shadow-lg">
                <h3 class="text-center mb-4">Профиль пользователя</h3>
                <div class="row">
                    <form>
                    
                        <div class="col-md-12 mb-3 text-center">
                            <img src="{% static "deps/images/baseavatar.jpg"%}"
                                alt="Аватар пользователя" class="img-fluid rounded-circle"
                                style="max-width: 150px;">
                            <input type="file" class="form-control mt-3" id="avatar"
                                accept="image/*">
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="firstName" class="form-label">Имя*</label>
                            <input type="text" class="form-control" id="firstName"
                                placeholder="{{user.first_name}}" value="{{user.first_name}}" required>
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="lastName" class="form-label">Фамилия*</label>
                            <input type="text" class="form-control" id="lastName"
                                placeholder="Введите вашу фамилию" value="{{user.last_name}}" required>
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="username" class="form-label">Имя пользователя*</label>
                            <input type="text" class="form-control" id="username"
                                placeholder="Введите ваше имя пользователя" value="{{user.username}}" required>
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="email" class="form-label">Email*</label>
                            <input type="email" class="form-control" id="email"
                                placeholder="Введите ваш email *youremail@example.com" value="{{user.email}}"
                                required>
                        </div>
                    </form>

                    <ul class="navbar-nav ms-auto mb-3 mb-lg-1" style="display:inline;" >
                        <li class="nav-item" style="float: left;margin-left: 12px">
                            <button type="submit" class="btn btn-dark" style="display:inline;">Сохранить</button>
                        </li>   

                        <li class="nav-item" style="float: right;font-size: 20px;">
                            <form action={% url "users:logout" %}>
                                <button type="submit" class="btn btn-light badge border bg-danger p-2">Выйти</button>
                            </form>
                        </li>
                    </ul>
                </div>
                
            </div>
        </div>
    </section>
{% endblock content %}

users/templates/users/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/deps/css/registration.css">
</head>

<body>
    <div class="container">
        <form action="{% url "user:registration" %}" method="post" id="regForm">
            {% csrf_token %}
            <h1>Регистрация</h1>

            <div class="input-group">
                <div class="input-field">
                    <label for="id_lastName">Фамилия*</label>
                    <input type="text" id="surename" 
                    name = "last_name"
                    placeholder="Введите вашу фамилию" 
                    value="{% if form.last_name.value %}{{ form.last_name.value}}{% endif %}"
                    required>
                    {% if form.second_name.errors %}
                        <div class="alter alter-danger alert-dismissible fade show">{{form.second_name.errors}}</div>
                    {% endif %}
                </div>
                <div class="input-field">
                    <label for="id_first_name">Имя*</label>
                    <input type="text" id="name" 
                    value="{% if form.first_name.value %}{{ form.first_name.value}}{% endif %}"
                    name="first_name"
                    placeholder="Введите ваше имя" required>
                    {% if form.first_name.errors %}
                                <div class="alter alter-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                {% endif %}
                </div>
            </div>

            <div class="input-group">
                <div class="input-field">
                    <label for="Логин">Логин*</label>
                    <input type="login" id="login"
                    value="{% if form.username.value %}{{ form.username.value}}{% endif %}"
                    name="username"
                    placeholder="Введите ваше имя пользователя" required>
                    {% if form.username.errors %}
                        <div class="alter alter-danger alert-dismissible fade show">{{form.username.errors}}</div>
                    {% endif %}
                </div>

                <div class="input-field">
                    <label for="Почта">Email*</label>
                    <input type="email" id="mail"
                    value="{% if form.email.value %}{{ form.email.value}}{% endif %}"
                    name="email"
                    placeholder="Введите ваш email" required>
                    {% if form.email.errors %}
                        <div class="alter alter-danger alert-dismissible fade show">{{form.email.errors}}</div>
                    {% endif %}
                </div>
            </div>

            <div class="input-group">
                <div class="input-field">
                    <label for="Пароль">Пароль*</label>
                    <input type="password" id="password"
                    value="{% if form.password1.value %}{{ form.password1.value}}{% endif %}"
                    name="password1"
                    placeholder="Введите пароль" required>
                    {% if form.password1.errors %}
                        <div class="alter alter-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                    {% endif %}
                </div>
                <div class="input-field">
                    <label for="Подтверждение пароля">Подтверждение пароля*</label>
                    <input type="password" id="passwordVerification"
                    value="{% if form.password2.value %}{{ form.password2.value}}{% endif %}"
                    name="password2"
                    placeholder="Подтвердите пароль" required>
                    {% if form.password2.errors %}
                        <div class="alter alter-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                    {% endif %}
                </div>
            </div>

            
            <button type="submit" class="btn">Зарегистрироваться</button>


        </form>
    </div>
</body>

</html>