book/urls.py
from django.urls import path

from book import views

app_name="book"

urlpatterns = [
    path("", views.library, name="index"),
    path("search/", views.book_search, name="book_search"),
    path("feedback", views.feedback, name="feedback"),
    path("<slug:book>/", views.book_detail, name="book_detail"),
    path('like_dislike', views.like_dislike, name='like_dislike'),
]

sitemi/urls.py
from django.contrib import admin
from django.urls import path, include
from sitemi import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("book.urls", namespace="book")),
    path("user/", include("users.urls", namespace="user")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import include, path
from users import views


app_name = "users"
urlpatterns = [
    path("registration", views.registration, name="registration"),
    path("", include("django.contrib.auth.urls")),
    path("profile", views.profile, name="profile"),
    path("logout", views.logout, name="logout"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="csrf-token" content="{{ csrf_token }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static "deps/css/style.css" %}" />
    {% block css %}
    
    {% endblock css %}
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    {% if header_bool %}
        <header>
            <nav class="navbar navbar-expand-lg">
                <div class="container-fluid">
        
                    <a class="navbar-brand" href="{% url "book:index" %}"><img src="../static/deps/images/logo.svg" alt=""
                            style="width: 100px;"></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
                            <li class="nav-item">
                                <a class="nav-link active" style="color: white;" aria-current="page" href="{% url "book:index" %}">Главная</a>
                            </li>
                        </ul>
        
                        <ul class="navbar-nav flex-grow-2 mx-auto mb-2 mb-lg-0 search">
                            <li>
                                <form class="d-flex flex-nowrap" role="search" method = "get" action = {% url "book:book_search" %}>
                                    <input class="form-control me-0 form-search" type="search" placeholder="Найти" aria-label="Search" name="query">
                                    <button class="btn btn-light btn-search" type="submit">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="17" height="25" fill="currentColor"
                                            class="bi bi-search" viewBox="0 0 16 16">
                                            <path
                                                d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0" />
                                        </svg>
                                    </button>
                                </form>
                            </li>
                        </ul>
        
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                            {% if request.user.is_authenticated %}
        
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url "user:profile" %}">Мой профиль</a>
                                </li>
        
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url "user:login" %}">Вход</a>
                                </li>
        
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url "user:registration" %}">Регистрация</a>
                                </li>
                            {% endif %}
                        </ul>
        
                    </div>
                </div>
            </nav>
        
            <!-- Поиск для мобильных устройств -->
            <ul class="navbar-nav flex-fill mx-auto mb-2 mb-lg-0 search-mobile">
                <li>
                    <form class="d-flex flex-nowrap" role="search">
                        <input class="form-control me-0 form-search" type="search" placeholder="Найти" aria-label="Search">
                        <button class="btn btn-light btn-search" type="submit">
                            <svg xmlns="http://www.w3.org/2000/svg" width="17" height="25" fill="currentColor"
                                class="bi bi-search" viewBox="0 0 16 16">
                                <path
                                    d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0" />
                            </svg>
                        </button>
                    </form>
                </li>
            </ul>
        </header>
    {% endif %}
    <section>
        <div class="container-fluid mt-4">

            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li class="{{ message.tags }}">
                            {{ message|safe }}
                            <a href="#" class="close">x</a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}

            {% block content %}
            {% endblock content %}
        </div>

    </section>

   {% block footer %}
   
   {% endblock footer %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>


</body>

</html>

templates/feedback.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<form class="form" method="post" action="{% url "book:feedback" %}" >
	{% csrf_token %}
	<div class="form__item">
		<input class="form__input" type="text" name="first_name" value="{{user.first_name}}" required>
		<label class="form__label">Ваше имя</label>
	</div>

	<div class="form__item">
		<input class="form__input" type="email" name="email" value = "{{user.email}}" required>
		<label class="form__label">Email</label>
	</div>

    <div class="form__item">
		<input class="form__input" type="text" name="comments" required>
		<label class="form__label">Ваш комментарий</label>
	</div>

	<input class="form__input btn_1" type="submit" value="Отправить">
	<input type="hidden" name="act" value="order">

</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% endblock content %}