book/urls.py
from django.urls import path

from book import views

app_name="book"

urlpatterns = [
    path("", views.library, name="index"),
    path("search/", views.book_search, name="book_search"),
    path("feedback", views.feedback, name="feedback"),
    path("<slug:book>/", views.book_detail, name="book_detail"),
    path('like_dislike', views.like_dislike, name='like_dislike'),
]

sitemi/urls.py
from django.contrib import admin
from django.urls import path, include
from sitemi import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("book.urls", namespace="book")),
    path("user/", include("users.urls", namespace="user")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models
from django.urls import reverse
from users.models import User
from django.conf import settings

class Author(models.Model):
    surname = models.CharField(max_length=80, verbose_name="Фамилия")
    name = models.CharField(max_length=80, verbose_name="Имя")
    patronymic = models.CharField(max_length=80, verbose_name="Отчество", blank=True)


    def __str__(self):
        return f"{self.surname} {self.name[0]}. {self.patronymic[0]}."
    

    class Meta:
        ordering=["surname"]
        verbose_name = "Автор"
        verbose_name_plural = "Авторы" 


class Book(models.Model):
    title = models.CharField(max_length=150, verbose_name="Название")
    slug = models.SlugField(max_length=150, unique_for_date="created")
    author = models.ManyToManyField(to=Author, verbose_name="Автор", related_name="books", symmetrical=False)
    image = models.ImageField(upload_to="books_images", blank=True, null=True, verbose_name="Изображение")
    created = models.DateTimeField(auto_now_add=True)
    likes=models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='likes', blank=True)
    url = models.URLField(blank=True, null=True, default="  ")

    class Meta:
        ordering=["title"]
        verbose_name = "Книга"
        verbose_name_plural = "Книги"
        indexes=[
            models.Index(fields=["title"])
        ]

    def get_absolute_url(self):
        return reverse("book:book_detail", args=[
            self.slug,
        ])

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'book')

book/forms.py
from django import forms
class UserForm(forms.Form):
    first_name= forms.CharField(max_length=100)
    email= forms.EmailField()
    comments = forms.CharField(max_length=500)


class SearchForm(forms.Form):
    query = forms.CharField()

book/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .forms import UserForm, SearchForm
from .models import Book
import requests
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import TrigramSimilarity



def library(request):
    books = Book.objects.all()
    
    context = {
        "title": "MIET books",
        "books": books,
        "header_bool": 1
    }

    return render(request, "book/index.html", context=context)


def feedback(request):
    submitbutton= request.POST.get("submit")
    firstname=''
    email=''
    comment=''
    if request.method == "POST":
        form = UserForm(request.POST or None)
        if form.is_valid():
            firstname= form.cleaned_data.get("first_name")
            email= form.cleaned_data.get("email")
            comment= form.cleaned_data.get("comments")
        url = "https://api.telegram.org/bot7079047712:AAHDhyunKU_Oe3p-5ZvVtEYZLPshFefdwO8/sendMessage"
        params={"chat_id": "1093577177", "parse_mode": "html", "text": f"{email}\n\n{firstname}:\n\n{comment}" }
        requests.get(url, params=params)
    else:
        form = UserForm()
    context = {
        "title": "Home - Авторизация",
        "form": form,
        "header_bool": 1
    }

    return render(request, 'feedback.html', context)


def book_detail(request, book):
    book = get_object_or_404(Book, 
                            slug = book)
    user_liked = book.like_set.filter(id=request.user.id).exists() if request.user.is_authenticated else False

    if book.likes.filter(id=request.user.id).exists():
        is_liked = True

    else:
        is_liked = False

    context = {
        'book': book,
        'user_liked': user_liked,
        "is_liked": is_liked,
        "header_bool": 1
    }

    return render(request, "book/bookProfile.html", context=context)

@login_required
@require_POST
@csrf_exempt
def like_dislike(request):
    user = request.user
    is_liked = None
    if not user.is_authenticated:
        return JsonResponse({'status': 'error', 'message': 'You must be logged in to like.'})

    book_id = request.POST.get('id')
    action = request.POST.get('action')

    try:
        book = Book.objects.get(id=book_id)


        if action == 'like':
            book.likes.add(request.user)
            is_liked = True
        else:
            book.likes.remove(request.user)
            is_liked = False

        total_likes = book.likes.count()
        return JsonResponse({'status': 'ok', 'total_likes': total_likes, "is_liked": True})
    except Book.DoesNotExist:
        return JsonResponse({'status': 'error', 'message': 'Book not found.'})
    except Exception as e:
        return JsonResponse({'status': 'error', 'message': str(e)})
    

def book_search(request):
    form = SearchForm()
    query = None
    results = []
    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            if query:
                results = Book.objects.annotate(similarity=TrigramSimilarity("title", query),).filter(similarity__gt=0.1).order_by("-similarity")
    return render (request, "book/search.html",
                   {"form_s": form,
                    "query": query,
                    "results": results,
                    "header_bool": 1,})

book/templates/book/bookProfile.html
{% extends "base.html" %}
{% load static %}
{% load author_tags %}

{% block css %}
<link rel="stylesheet" href="{% static 'deps/css/bookProfile.css' %}"/>

<style>
    body {
        /--font-family: Arial, sans-serif;--/
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        background-color: #f4f4f9;
    }

    .book-profile {
        display: flex;
        justify-content: center;
        align-items: flex-start;
        padding: 2em;
        gap: 2em;
        background-color: #fff;
        margin: 50px auto;
        max-width: 1500px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
    }

    .book-image img {
        width: 100%;
        height: auto;
        border-radius: 10px;
    }

    .book-image {
        flex: 1;
        max-width: 400px;
        border-radius: 10px;
        overflow: hidden;
    }


    .book-info-section{
        flex: 2;
        flex-direction: column;
        border-radius: 10px;
    }


    .book-info {
        padding: 1em;
        background-color: #fafafa;
        border-radius: 10px;
    }

    .book-info h1 {
        font-weight: bold;
        font-size: 2.5em;
        margin-bottom: 1em;
        color: #333;
        align-content: center;
    }

    .book-info label {
        font-weight: bold;
        font-size: 1.2em;
        color: #555;
    }

    .book-info p {
        font-size: 1.1em;
        margin: 0.5em 0 1em;
        color: #666;
    }

    .button-container {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 2em;
    }

    .btn_3 {
        margin: 30px;
        height: 50px;
        padding: 0 2em;
        border-radius: 11px;
        background-color: #21a0d6b5;
        border: none;
        color: #fff;
        font-size: 1.2em;
        cursor: pointer;
        transition: background-color 0.3s ease;
        text-decoration: none;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .btn_3:hover {
        background-color: #1a84b8b5;
    }

    .like-container {
        margin-top: 90px;
        padding-left: 42%;
        align-items: center;
    }

    .like-container img {
        cursor: pointer;
    }

    .like-container .count {
        margin-left: 0.5em;
        font-size: 1em;
        color: #555;
    }
    

    
    
    @media (max-width: 900px) {
        .book-profile {
            max-width: 850px;
            flex-direction: column;
            align-items: left;
            padding: 1em;
        }

        .book-image, .book-info-section {
            padding-left: 3em;
            width: 50%;
            max-width: none;
        }
        

        .book-info h1 {
            font-size: 2em;
            text-align: center;
        }

        .book-info p, .book-info label {
            text-align: center;
        }

        .button-container {
            margin-top: 1em;
        }

        .btn_3 {
            width: 100%;
            max-width: 300px;
        }
        .like-container {
            margin-top: 10px;
            padding-left: 38%;
            align-items: center;
        }
        

    }
</style>   
{% endblock css %}

{% block title %}
Book profile
{% endblock title %}

<!--<div class="bookProfile">
    <div class="pic">
        <img src="#" alt="">
    </div>
    <div class="info">
        <p1></p>
    </div>
</div>-->

{% block content %}

    <div class="book-profile">
        <div class="book-image">
            <img src={{  book.image.url  }} alt="Обложка книги">
        </div>
        <div class="book-info-section">
            <div class="book-info">
                <h1>{{book.title}}</h1>
                <div class="first-block">
                    <label for="Автор" class="label">Автор:</label>
                    <p>{% author book.author.all %}</p>
                </div>
    
                <div class="second-block">
                    <label for="Дисциплина" class="label">Наименование дисциплины:</label>
                    <p>{{book.title}}</p>
                </div>
                
                
                <div class="button-container"><button type="submit" class="btn_3"><a href={{book.url}}>Читать</a></button></div>
            
            </div>

            <div class="like-container">
                <a href="#" class="like" data-id="{{ book.id }}" data-action="{% if is_liked %}unlike{% else %}like{% endif %}">
                    {% if is_liked %}
                        <img src="{% static 'deps/images/Like.png' %}" alt="{% if user in book.like_set.all %}Unlike{% else %}Like{% endif %}">
                    {% else %}
                        <img src="{% static 'deps/images/Unlike.png' %}" alt="{% if user in book.like_set.all %}Unlike{% else %}Like{% endif %}">
                    {% endif %}
                </a>
                <span class="count"><span class="total">{{ book.likes.count }}</span> Likes</span>
            </div>
            
        </div>
        



    </div>

    
    
    <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var t = "{{ lis }}";
        if (t.length !== 0){
            console.log("Лайкнуто ли: ", t);
        }
        else{
            console.log("0")
        }

        
        const csrftoken = getCookie('csrftoken');
    
        const url = "{% url 'book:like_dislike' %}";
        var options = {
            method: "POST",
            headers: {"X-CSRFToken": csrftoken},
            mode: "same-origin"
        }
    
        document.querySelector("a.like").addEventListener("click", function(e){
            e.preventDefault();
            var t = "{{ lis }}";
            if (t.length !== 0){
                console.log("Лайкнуто ли: ", t);
            }
            else{
                console.log("0")
            }
            var likeButton = this;
    
            var formData = new FormData();
            formData.append("id", likeButton.dataset.id);
            formData.append("action", likeButton.dataset.action);
            options["body"] = formData;
    
            fetch(url, options)
            .then(response => response.json())
            .then(data => {
                if (data["status"] === "ok")
                {
                    var previousAction = likeButton.dataset.action;
                    var action = previousAction === "like" ? "unlike" : "like";
                    likeButton.dataset.action = action;
    
                    var likeImage = likeButton.querySelector('img');
                    likeImage.src = action === "like" ? "{% static 'deps/images/Unlike.png' %}" : "{% static 'deps/images/Like.png' %}";
                    likeImage.alt = action.charAt(0).toUpperCase() + action.slice(1);
    
                    likeButton.innerHTML = '';
                    likeButton.appendChild(likeImage);
                    //likeButton.append(action.charAt(0).toUpperCase() + action.slice(1));
    
                    var likeCount = document.querySelector("span.count .total");
                    likeCount.innerHTML = data.total_likes;
                }
            })
            .catch(error => console.error('Error:', error));
        });
    </script>
    
    


{% endblock content %}

book/templates/book/index.html
{% extends "base.html" %}
{% load static %}
{% load author_tags %}


{% block title %}{{ title }}{% endblock  %}


{% block content %}
<div class="row">
    <div class="col-lg-2">
        <!-- Боковая панель -->
    </div>

    <div class="col-lg-9 col-md-12">

        <div class="row">
            {% for book in books  %}
            <div class="col-lg-4 col-md-6 mt-4 mb-5">
                <div class="card">
                    
                    <a href="{{book.get_absolute_url}}">
                        <img src={{  book.image.url  }} class="card-img-top"
                            alt="Учебник">
                        <div class="card-body">
                            <p class="card-text-name">{{  book.title  }}</p>
                            <p class="card-text-author">{% author book.author.all %}</p>
                            <a href="{{book.get_absolute_url}}" class="btn btn-primary">Подробнее</a>
                        </div>
                    </a>

                </div>
            </div>
            {% endfor %}


        </div>
    </div>

    <div class="col-lg-1 col-md-1">
        <!-- Боковая панель -->
    </div>

</div>
{% endblock content %}


{% block footer %}
    {% if header_bool %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <a href="{% url "book:feedback" %}">
                <p class="m-0 text-center text-white">Обратная связь</p>
            </a>
        </div>
    </footer>
    {% endif %}
{% endblock footer %}

book/templates/book/search.html
{% extends "base.html" %}
{% load static %}
{% load author_tags %}

{% block title %}Search{% endblock title %}

{% block content %}
    {% if query %}
        {% if results.count %}
            <h4> Показываем результаты по запросу "{{  query  }}", {{ results.count }} результатов</h4>
        {% else %}
            <h4> По запросу "{{  query  }}" ничего не нашлось. Похоже, у нас такого нет. </h4>
            <p>Но на всякий случай советуем проверить опечатки в запросе.</p>
        {% endif %}
        
    {% else %}
        <h4>Похоже вы ничего не ввели</h4>
    {% endif %}
    {% include "book/index.html" with books=results header_bool=0 %}
{% endblock content %}